apiVersion: v1
kind: Service
metadata:
  name: myguide-api-service
  namespace: myguide-api
spec:
  selector:
    app: myguide-api
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30021
